on:
  pull_request:

name: Run Tests
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Build and Test
        run: mvn install

      - id: branch-coverage-percentage
        name: Extract branch coverage percentage
        run: |
          mvn jacoco-console-reporter:report |
          grep "all classes" |
          awk '{print $(NF-4)}' |
          tr -d '%' |
          sed 's/\./,/' |
          { read coverage; echo "COVERAGE=$coverage"; } >> $GITHUB_OUTPUT

      - id: pitest-test-strength-percentage
        name: Extract test strength percentage
        run: |
          mvn pitest:mutationCoverage |
          grep -oE '[0-9]+%' |
          tail -n 1 |
          tr -d '%' |
          { read mutation; echo "MUTATION=$mutation"; } >> $GITHUB_OUTPUT

      - name: Install redis
        run: sudo apt-get update && sudo apt-get install -y redis-tools

      - id: echo-coverage
        name: Echo coverage
        env:
          REDIS_URL: ${{ secrets.REDIS_CONNECTION_STRING }}
          COVERAGE: ${{ steps.branch-coverage-percentage.outputs.COVERAGE }}
          MUTATION: ${{ steps.pitest-test-strength-percentage.outputs.MUTATION }}
          USER: "${{ github.event.pull_request.user.id }}-${{ github.event.pull_request.user.login }}"
        run: |
          redis-cli --tls -u "$REDIS_URL" ZADD unit-tests "$((($COVERAGE + $MUTATION)/2))" "$USER"